### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by daidoji**
Updated Meetings link to point to WebOfTrust KERI readme with meeting info and linked to discord invite as opposed to Slack.

### CODE REVIEW

**Comment by jasoncolburne** [comment]
Thank you Charles!

**Comment by jasoncolburne** [comment]
Actually they should probably be another PR. I'll spin one up.

**Comment by jasoncolburne** [comment]
#152 looks like it should pass. hopefully we can merge it soon and then pull those changes into this PR.

**Review by m00sey — APPROVED** [review]
📜

**Pull request merged**
