### PR TITLE
add ECDSA_256r1N in condition when checking if code is transferable

### PR DESCRIPTION
**Pull request by Arsh-Sandhu**

### CODE REVIEW

**Review by qui-jason — DISMISSED** [review]
Thanks for catching this! @pfeairheller not sure if this was also missed in the KERIpy work, I know you initially took a look at my changes when creating that branch

**Review by jasoncolburne — APPROVED** [review]
Whoops, wrong account. LGTM

**Comment by Arsh-Sandhu** [comment]
> Thanks for catching this! @pfeairheller not sure if this was also missed in the KERIpy work, I know you initially took a look at my changes when creating that branch

I fixed this in KERIpy, added `ECDSA_256r1N` in `NonTransCodex` class

[Commit d78d762](https://github.com/WebOfTrust/keripy/pull/490/commits/d78d76253f364205e8e7170ec510eae92ad4bc9b#diff-f55a5aa13d6e2d04f9c6a12d9738b139cc2e0f91bfabde451621a8875ee04737R605 )

**Comment by Arsh-Sandhu** [comment]
> @Arsh-Sandhu Looks like you need to run `cargo fmt`. Also, you probably want to run the `make preflight` command to ensure things are going to pass CI. Would you mind also bumping the version in `Cargo.toml` to 0.6.1?

sure

**Review by m00sey — APPROVED** [review]
:rocket:

**Pull request merged**
